import { mkdir, cp, rm, stat } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const input = resolve(root, 'site');
const output = resolve(root, 'dist');
await stat(resolve(input, 'index.html'));
await rm(output, { recursive: true, force: true });
await mkdir(output, { recursive: true });
await cp(input, output, { recursive: true });
console.log('Balisha V1: static site copied from site/ to dist/');
